services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8081:8000'
        tty: true
        stdin_open: true
        volumes:
            - '.:/var/task'
        # Entrypoint forzado para evitar que el contenedor se apague al iniciar
        entrypoint: ["tail", "-f", "/dev/null"]
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:8081
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=s3_smart_vault
            - DB_USERNAME=sail
            - DB_PASSWORD=password
        networks:
            - vault_network
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '33060:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=s3_smart_vault
            - MYSQL_USER=sail
            - MYSQL_PASSWORD=password
        networks:
            - vault_network

networks:
    vault_network:
        driver: bridge