service: s3-smart-vault

provider:
  name: aws
  region: us-east-1
  architecture: x86_64
  environment:
    APP_ENV: production
    APP_KEY: ${env:APP_KEY}
    ASSET_URL: https://s3-smart-vault-assets-terracreativa.s3.amazonaws.com
    SESSION_DRIVER: cookie
    LOG_CHANNEL: stderr
    VIEW_COMPILED_PATH: /tmp/storage/framework/views

functions:
  web:
    image: 893159412786.dkr.ecr.us-east-1.amazonaws.com/serverless-s3-smart-vault-dev:latest
    timeout: 28
    events:
      - httpApi: '*'

plugins: []